baseURL: "https://adityamittal03.github.io" 
title: Aditya Mittal's Homepage
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: books/
          weight: 2
        - name: Publications
          url: papers/
          weight: 3
        - name: Education & Professional Experience
          url: courses/
          weight: 4
        - name: Projects
          url: data/
          weight: 5
        - name: CV
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "Hi! I am a fourth-year undergraduate student at UC Davis majoring in Statistics with minors in Mathematics and Computer Science. 
                  My research focuses on developing novel algorithms that promote trustworthiness in machine learning and responsible AI systems. I am broadly interested in algorithmic fairness-related issues—particularly in quantifying and mitigating bias in predictive modeling applications."
    author: Aditya Mittal
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "December 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Aditya Mittal
          subtitle: "Hi! I am a fourth-year undergraduate student at UC Davis majoring in Statistics with minors in Mathematics and Computer Science.
                     My research focuses on developing novel algorithms that promote trustworthiness in machine learning and responsible AI systems. I am broadly interested in algorithmic fairness-related issues—particularly in quantifying and mitigating bias in predictive modeling applications."
          imageUrl: "me.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: adimittal@ucdavis.edu
        - name: Phone
          url: adimittal@ucdavis.edu
        - name: Google Scholar
          url: https://www.zoom.us/my/igelfeld
        - name: GitHub
          url: location/
        - name: LinkedIn
          url: officehours/
        - name: Twitter
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Aditya Mittal's Homepage"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
